version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
    command: sleep infinity
    network_mode: service:postgres
    user: vscode
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: devdb

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data: